### ISSUE TITLE
Tensorboard not toggling runs

### ISSUE THREAD

**Issue by pseeth** [guildai/guildai#223] opened 2020-08-12 20:49 UTC
When I go to use tensorboard, there are two things that seem to be happening:

1. I can't toggle runs in the side. If I try, I get this error in the console.

```
tf-tensorboard.html.js:14590 Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at build://tf-tensorboard/tf-tensorboard.html.js:14590:440
    at x (build://tf-tensorboard/tf-tensorboard.html.js:14586:270)
    at HTMLElement._storeRunSelectionState (build://tf-tensorboard/tf-tensorboard.html.js:14587:466)
    at Object.runObserverEffect [as fn] (build://tf-tensorboard/tf-tensorboard.html.js:3123:10)
    at runEffectsForProperty (build://tf-tensorboard/tf-tensorboard.html.js:3068:14)
    at runEffects (build://tf-tensorboard/tf-tensorboard.html.js:3034:13)
    at HTMLElement._propertiesChanged (build://tf-tensorboard/tf-tensorboard.html.js:4568:9)
    at HTMLElement._flushProperties (build://tf-tensorboard/tf-tensorboard.html.js:1938:18)
    at HTMLElement._flushProperties (build://tf-tensorboard/tf-tensorboard.html.js:4416:15)
    at HTMLElement._invalidateProperties (build://tf-tensorboard/tf-tensorboard.html.js:4388:16)
```

2. It seems that when running experiments with Guild, _regular_ tensorboard no longer picks up my log files? I can only see the results when using `guild view`. But running `tensorboard --logdir=...` with `logdir` pointing to my runs directory picks up zero log files somehow. I thought this might be because of too many runs so I removed many of my broken runs, but it's still broken.

Other than the above, loving Guild so far - thanks for a great project!

**Comment by gar1t** [comment] 2020-08-13 15:04
Could you run `guild check` and provide the following attributes?

- guild_version
- python_version
- platform
- tensorboard_version

**Comment by pseeth** [comment] 2020-08-13 17:00
Sorry about that, here you go:

```
$ guild check
guild_version:             0.7.0.post1
guild_install_location:    /home/admin/miniconda3/envs/research/lib/python3.8/site-packages/guild
guild_home:                /home/admin/miniconda3/envs/research/.guild
guild_resource_cache:      /home/admin/miniconda3/envs/research/.guild/cache/resources
installed_plugins:         cpu, disk, exec_script, gpu, keras, memory, perf, python_script, queue, skopt
python_version:            3.8.5 | packaged by conda-forge | (default, Jul 31 2020, 02:39:48) [GCC 7.5.0]
python_exe:                /home/admin/miniconda3/envs/research/bin/python
platform:                  Linux 4.15.0-99-generic x86_64
psutil_version:            5.6.3
tensorboard_version:       2.2.0
cuda_version:              not installed
nvidia_smi_version:        440.64.00
latest_guild_version:      0.7.0.post1
```

**Comment by gar1t** [comment] 2020-08-13 17:45
It's hard to say without seeing your runs. The error message suggests a UTF issue, which would likely come by way of a file system path.

I suggest trying to reproduce this with a single run in an empty environment. You can export (move) your existing runs to a temporary location to be restored later. Or just create a new environment, activate it, and then run a simple script. E.g. https://github.com/guildai/guildai/blob/master/examples/get-started/train.py.

If you can reproduce this in that simplified environment we can tackle it from there. If you can't reproduce it in a new environment with a simple example, then the process is finding the run that's causing the error. Again my suspicion is that there's something in the file names that's causing issues. Since the file names contain flag labels, a non-latin flag value could possibly be causing the issues.

**Comment by pseeth** [comment] 2020-08-16 08:14
Will work on reproducing at some point. But I wanted to mention that I got `guild view` working much nicer after discovering the ability to only do view on _marked_ runs. So I mark the runs I want to compare, then do `guild view -M` and tensorboard works great, is no longer sluggish trying to load hundreds of runs, etc.

**Comment by gar1t** [comment] 2020-08-17 11:34
That's a good strategy. Btw the behavior of TensorBoard should be the same
whether you run with `guild tensorboard` or from `guild view`. If you're
seeing inconsistencies between the two, please let us know.

Also as a tip, to help focus on a subset of runs, you can try a couple
other things.

Use the new `--tag` option with the label command to modify a run label.
Use that tag with the --label/-l option to filter. This is like marking but
more flexible.

Export runs with the --move option into sub-directories to keep your
working set small. Use a meaningful names for your subdirectories to
organizes your archives runs. You can list the runs in a directory using
`guild runs -A <dir>`. You can import runs back with the import command.

**Comment by JanRuettinger** [comment] 2020-09-04 08:49
@gar1t Is it possible to limit `guild view` to a subdirectory? I have moved a collection of runs to a subdirectory and now I would like to do `guild view subdirectory` but this doesn't work.

**Comment by gar1t** [comment] 2020-09-09 12:54
No, it's not possible. But this is extremely reasonable and I have a thought as to what we could do here. I created #232 to track this.

To do what you want, you'd need to finagle a Guild *home* directory structure and use `guild -H <dir>`. You could do this using `import`:

```
$ guild -H <location for a new Guild home> import --move <your current subdirectory>
```

This will create a new location for Guild home, under which you'll see a `runs` directory. This will contain your list of runs. You can then use `guild -H <new guild home> view` to accomplish what you want.

#232 is a proposal to make this simply `guild -R <your current subdirectory> view`.

**Comment by gar1t** [comment] 2021-03-25 23:55
I see this is a duplicate of #232 so I'll close here and we can use the other to track progress. If I got that wrong, please feel to reopen.

**Closed as completed by gar1t** 2021-03-25 23:55 UTC
Labels: duplicate
