### ISSUE TITLE
Guild run --restart keeps old tensorboard logs

### ISSUE THREAD

**Issue by FelixAbrahamsson** [guildai/guildai#145] opened 2020-03-13 09:04 UTC
When I run `guild run --restart <run_id>` it seems that the tensorboard logs from the old runs remain (which messes up tensorboard for the new run). I'm guessing when I restart a run, guild copies over all files from the old run, even the output files. Would it be reasonable to only copy over sourcecode and resources?

**Comment by gar1t** [comment] 2020-03-13 10:57
The `--restart` option restarts the run process in the same run directory. It does not delete, copy, or otherwise modify files in that run directory. So what you're seeing there is by design.

You may want to use the `--rerun` option. This generates a new run using the flags from the original run by default. (An important aside, I see that `--rerun` is not working as expected in the `0.7` pre-release. This will be fixed before the final release.)

The current implementation of `--rerun` does not re-use source code or necessarily the same resources as the first run. It will use the current source code for the project. And the resources will be re-resolved based on any modified flag values.

`--restart` is literally "restart this run where you left off". It's used generally when a run is terminated and you want to restart the process in the same run directory - nothing at all having been changed b Guild.

`--rerun` is "I want to run this again and don't want to make sure the flag values are the same". Generally in this case you're re-running because you've changed the source code and want to try those changes using the same settings.

You may be talking about something in-between potentially.

**Comment by gar1t** [comment] 2020-03-13 11:58
As complex as the `run` command is (though in fairness, ever tried `man gpg`? ;) I think we might be looking at another run option, which indicates that source code should be preserved for a `--rerun` scenario.

I can see how rerunning an operation without controlling the source code would be a bad idea.

There are two scenarios, both of which are quite legit:

1. Re-run with the same flags, but using modified project source
2. Re-run with different flags using the same source

The second case is practically impossible today, while the first option simply requires that you re-specify the flags (maybe a pain but not impossible)

So then the question, what's the best default behavior? When re-running (i.e. using `--rerun` - NOT `--restart`) should Guild use the working project code (i.e. apply current source code rules to the working project) or use the original run source code by default?

Guild should follow the principle of least surprise here. My personal least surprise scenario is that Guild uses the working source code by default. But that's because I use `--rerun` as a way to quickly bring up a set of flags based on an earlier run.

My thought for the option name here:

- `--keep-sourcecode` - in the case where default is to use working copy
- `--use-working-sourcecode` - in the case where default is to use original run source code

**Comment by FelixAbrahamsson** [comment] 2020-03-16 17:50
So my situation was that I wanted to rerun an operation with the original source code and flags, because the run had crashed for reasons not related to guild or the source code (and in the meantime the code had undergone changes). I wouldn't say this is a common use case so it probably shouldn't be the default behavior of `rerun` to reuse source code, but I think it would be nice if it was supported. Your option names sound good to me!

**Comment by gar1t** [comment] 2020-03-16 18:18
One of the problems is that the terms `rerun` and `restart` are closely related (in English) and it's not obvious which is which here. The have very different meanings in Guild though.

When a run crashes, I would recommend using `--restart`. This will literally restart the process using the same everything - in the same run directory. There's no copying.

Generally when a TensorFlow process is restarted, the TensorBoard logs just do the right thing. This is by careful design (by Google/TensorFlow team) so if you're seeing something broken there I'd be curious what that is.

That said - and this might be the issue - it's up to your code to look for checkpoints and load them - and update the global step with the latest from the checkpoint. This is a PITA to do manually, but it's the only correct approach for restarting early terminated runs.

TF may have a scheme that does this more smoothly. The last time I looked at this, the developer had to do this him/herself.

One way to test this would be to run without Guild. Pick an output/log/checkpoint dir and re-use it after terminating a run after a checkpoint is written (e.g. `Ctrl-C`). Then run that same Python command (again, no Guild) and see if your code does the right thing - i.e. detects previous checkpoints, restores the graph using the latest, and updates the global step used. It should resume  the training run and the TB event logs should be correct.

**Comment by gar1t** [comment] 2020-05-26 22:40
0.7 changes the option `--rerun` to `--proto` to help steer clear of this confusion.

Use `--restart` to restart a run in-place. You can redefine flag values as needed. This is useful for restarting a failed run. By default, Guild uses the original source code for the run. But if you're restarting because you've made a code change and want to apply it, include `--force-sourcecode` in the command - Guild will use the latest working source code for the restart.

Use `--proto` to use a run flags and source code as a prototype for a new run (this used to be `--rerun`). Use this when you want a new run, but want to base it off an existing run. You can use `--force-sourecode` with this option to apply the working source code to the new run.

To your original issue - I think that's the behavior you want. Whatever files are generated in the run are there for a restart. If logs are written with earlier steps, which does mess up TensorBoard, the operation needs to be smart restarts and look for existing logs, read them to get the latest step, and resume accordingly. This is a bit advanced, but any of the more serious deep learning examples (those from Google come to mind) have code that shows how to do this.

**Comment by gar1t** [comment] 2020-07-16 19:00
The fix is now generally available in 0.7.0. If this is still an issue, please re-open and we'll sort it out. Thanks again for the report!

**Closed as completed by gar1t** 2020-07-16 19:00 UTC
