### ISSUE TITLE
Reversing `guild runs publish`?

### ISSUE THREAD

**Issue by uduse** [guildai/guildai#373] opened 2022-04-14 06:30 UTC
Is there a way to undo publishing runs? I'm currently just deleting all files under `.guild/runs/published-runs` then do the publishing again. Is this the right thing to do?

**Comment by gar1t** [comment] 2022-04-14 16:59
If `.guild/runs` is the directory where Guild is storing runs - i.e. `$GUILD_HOME/runs` - then you don't want to store published runs there. I assume you're running Guild commands from `.guild/runs` and that's why you're seeing that directory in there. It might be a good idea for Guild to warn you about that. (Guild is going to inspect that `published-runs` dir as if it were a run directory, so it's a good idea to leave that directory alone unless you need to hack the files there for some reason.)

But to your question, Guild doesn't clean the target directory beforehand by design - it adds new runs but doesn't delete existing run. If you want to clean that directory before publishing, I suggest doing what you're doing. I think that's the right pattern - to use the file system to prepare the target (in this case by deleting it, or its contents) and then run the Guild command.

**Comment by uduse** [comment] 2022-04-14 21:28
@gar1t It seems I should tag runs that I would like to publish and publish to a directory managed by myself. If I want to edit the published runs, re-tag runs then publish it again. How does this sound?

**Comment by gar1t** [comment] 2022-04-14 21:43
Hmm, I'm not sure I understand. The publish commands supports a user-defined directory ('published-runs' is just the default - and that directory is created in the current directory). So you can run `guild publish -t foo -d foo-tagged-runs` for any variety of tags. If you edit the contents of the published runs you might consider using a custom template. This is an under-documented (I think zero docs, ugh) feature that I can help you with. That way you don't ever need to edit things manually.

As far as re-tagging runs, this I don't follow. If you're using tags to select files for publish, why not just specify the runs directly in the publish command - i.e. by specifying IDs?

**Comment by uduse** [comment] 2022-04-14 22:53
Oh I didn't know `published-runs` is generated in the current directory. I was using it in my `$GUILD_HOME` so it appeared that it generates the directory in parallel to other run directories. I don't edit my runs so I guess I don't need to customize template, the current publishing is good enough for me. By re-tagging I mean it would be more convenient for me to select runs that I want to publish.

**Comment by gar1t** [comment] 2022-04-28 17:28
Cool! I'm going to close this one. If you have further questions or want advice on something, take a look at https://my.guild.ai - that's an alternative to GitHub issues that might get more eyeballs (as a community site).

**Closed as completed by gar1t** 2022-04-28 17:28 UTC
