### ISSUE TITLE
'guild: command not found' using remote conda environment

### ISSUE THREAD

**Issue by SebastianCallh** [guildai/guildai#150] opened 2020-03-17 15:32 UTC
I am experiencing some issues trying to run a remote job in a conda environment. I set it up so I can ssh onto `my-remote`, run `conda activate guild` and then have `guild` on my path. I tried to put this into the `~/.guild/config.yml` as  

    remotes:
        my-remote:
            type: ssh
            host: my-remote
            user: sebastian.callh
            guild-home: /home/sebastian.callh/anaconda3/envs/guild/.guild
            conda-env: guild

which should be consistent with [the implementation](https://github.com/guildai/guildai/blob/caf6b4f6a9333ff7ee02c29bdd62d17ace647d56/guild/remotes/ssh.py#L373) but when running `guild run test:train -r my-remote` I get

    ...
    Initializing remote run
    Copying package
    sending incremental file list
    test-0.0.0-py2.py3-none-any.whl

    sent 2,077 bytes  received 35 bytes  1,408.00 bytes/sec
    total size is 1,948  speedup is 0.92
    Installing package and its dependencies
    bash: guild: command not found.

The output of `conda activate guild && guild check` on `my-remote` is 

    guild_version:             0.7.0.rc9
    guild_install_location:    /home/sebastian.callh/anaconda3/envs/guild/lib/python3.8/site-packages/guild
    guild_home:                /home/sebastian.callh/anaconda3/envs/guild/.guild
    guild_resource_cache:      /home/sebastian.callh/anaconda3/envs/guild/.guild/cache/resources
    installed_plugins:         cpu, disk, exec_script, gpu, keras, memory, perf, python_script, queue, skopt
    python_version:            3.8.1 (default, Jan  8 2020, 22:29:32) [GCC 7.3.0]
    python_exe:                /home/sebastian.callh/anaconda3/envs/guild/bin/python
    platform:                  Linux 4.15.0-70-generic x86_64
    psutil_version:            5.6.3
    tensorboard_version:       2.1.1
    cuda_version:              not installed
    nvidia_smi_version:        430.26
    latest_guild_version:      0.6.6.

I expect it to activate the `guild` environment and find `guild`, but does not seem to be the case. What am I missing here?

**Comment by gar1t** [comment] 2020-03-17 15:39
A couple things: you can drop `guild-home` from the remote def. The fact you're specifying `conda-env` will tell Guild where Guild home is.

Run `guild check -r my-remote` to check connectivity and info to the remote.

If that still shows `guild: command not found` then run `guild --verbose check -r my-remote`. That will be a lot more output so if you'd like to post that via gist or file attachment, feel free!

If you feel any output contains sensitive information (just scan it over and judge for yourself) then you can post privately on the [Slack workspace](https://bit.ly/guild-ai-slack).

**Comment by SebastianCallh** [comment] 2020-03-17 15:50
Thank you for the quick response and for the pointer about `guild-home`.

Running  `guild check -r my-remote` does indeed return `bash: guild: command not found`, so I tested `guild --verbose check -r my-remote`. However, that returns `guild: unrecognized option '--verbose'`. Don't suppose you mean `guild check --verbose -r my-remote`? That command runs but returns the same as `guild check -r my-remote`. It does work when i manually ssh though, and shows that I do not have `twain` or `tensorflow` installed.

**Comment by gar1t** [comment] 2020-03-17 15:53
Sorry, that was supposed to be `--debug`.

**Comment by gar1t** [comment] 2020-03-17 15:56
The issue is likely a `PATH` difference between logging in over ssh and running a command over ssh. Systems configure the path differently based on how ssh is run.

Off the top, this might help: https://unix.stackexchange.com/questions/332532/how-to-set-path-when-running-a-ssh-command

In the meantime I'll keep looking for some more info - maybe some better guides for this problem.

**Comment by SebastianCallh** [comment] 2020-03-17 16:06
Gotcha! I'm experimenting with some different solutions.

Before I forget, I want to mention that the reason `tensorflow` was missing was because the `conda` environment was using Python 3.8, and `tensorflow` requires <= 3.7.  Creating a new Python 3.7 environment and installing `guild` properly registered `tensorflow`. So it looks like `guild` has an implicit Python version bound of <= 3.7.

**Comment by gar1t** [comment] 2020-03-17 16:11
Guild should not in any way require TensorFlow (it does require TensorBoard). If you're spotting something breaking (without a coherent error message) when TF is not installed, that's a bug.

**Comment by SebastianCallh** [comment] 2020-03-17 16:18
Not breaking exactly, but `guild check` reports

    ...
    tensorflow_version:        not installed (No module named 'tensorflow')
    ...
    guild: there are problems with your setup

which is slightly confusing if it is not required. It does list `tensorboard` as well like you said. Maybe the row about `tensorflow` ought to be removed?

**Comment by gar1t** [comment] 2020-03-17 16:23
Yeah, "not installed" is okay, but that error message there I think should be hidden unless `--verbose` is used.

There is likely an actual problem there though (not related to TF). Are there any other error-like messages in that output? You can also use `--verbose` to check and show more details.

**Comment by SebastianCallh** [comment] 2020-03-17 16:29
There's the line `twine_version:             NOT INSTALLED (No module named 'twine')` as well. It does not seem related to this issue though; I confirmed that the paths are different when running an ssh command and ssh:ing manually. Conda is not on the path when running a command. I've yet to solve it though.

I can open another issue for the installed output stuff.

**Comment by SebastianCallh** [comment] 2020-03-17 17:26
I think you're quite right about the discrepancy in PATH being the problem. And  it looks tricky  to solve to boot.

Since I do not control how the ssh commands are executed (that happens inside `guild`) I cannot  `source  .bashrc` before executing them. And I do not have root access to the remote machine so I cannot add conda to the path through  `~/.ssh/environment` (`PermitUserEnvironment` is set to `no`). 

It feels like I can't possibly be alone in this situation, though I've not seen any issues on the matter before opening this one. One idea I have is maybe it is possible to somehow forward the SSH to a docker container where guild is installed, circumventing the conda stuff. It feels like a fairly heavyweight solution though.

**Comment by gar1t** [comment] 2020-03-17 19:29
We'll take this on. I'll mark this as a bug - I think Guild should just work in this case.

In the meantime, let's see if we can find a work around.

Are you able to install Guild from outside the conda env - e.g. in your user location?

E.g. ssh to the system and run this (not activating the conda env):

```
pip install guildai --user --pre
```

This may make Guild available on the path used for ssh commands.

If that doesn't work, could you run `test-path` from this Guild file on the remote?

https://github.com/guildai/issue-resolution/blob/master/150-guild-command-not-found-using-remote-conda-environment/guild.yml

This will show the remote path. Assuming you can't change this, your shot here is to create a symlink `guild` somewhere in that path (i.e. a path you can write to) that points to a Guild installation.

**Comment by SebastianCallh** [comment] 2020-03-18 06:52
Pip is installed through conda (it's not installed globally), so I have to be in some sort of conda environment to install Guild. 

Running the `test-path` command shows the "proper" path, since I ssh through a shell .bashrc is run and the conda script in there populates the path.  I did however, try running a bash file with contents `echo $PATH` through "ssh my-remote my-file.sh" and by manually ssh:ing and then running it. This shows the discrepancy in the PATH.

Using a symlink is a really nice idea. Wouldn't a symlink to conda be better and a bit more flexible though? Then the `conda-env` should be able to find the correct environment, and then we would be in business.

**Comment by gar1t** [comment] 2020-03-18 13:17
I'm not sure what you mean by a symlink to `conda`. I agree that Guild should be able to find the remote Guild by looking in an env without having to mess with paths. That's extremely reasonable - so considering this a bug.

The symlink to Guild within your existing (non command) PATH is a work-around until the fix for this issue is released.

**Comment by SebastianCallh** [comment] 2020-03-18 13:38
Using a symlink did indeed work!

I was thinking that the issue was that `conda` was not on the path when running ssh commands so the environment where `guild` was installed never got activated and hence the above error arose.

And while `guild` is now found when running remote commands, it does not seem to use the Python provided by the supplied `conda-env`. 
Running a command like 

    test-path:
      exec: bash -c 'which python'

shows `/usr/bin/python`, (the same as in `guild check`) but I am expecting it to show the path to my conda environment. Is this intended behaviour?

**Comment by gar1t** [comment] 2020-03-18 13:39
Are you able to edit the activation script for the conda environment? Guild runs this before running anything else - so you will be able to set the `PATH` env to find Guild.

There's a `venv-activate` attribute associated with the remote that lets you explicitly activate the environment. You can run something like `source <path_to_env_file>` in the remote:

```
remotes:
  my-remote:
    venv-activate: source /path/to/env/file
```

If `PATH` is set via that env file, Guild will be available for commands.

**Comment by gar1t** [comment] 2020-03-18 13:48
The environment is not likely available on the PATH used by ssh commands. That's the issue here.

I updated the issue resolution doc here with some workaround notes:

https://github.com/guildai/issue-resolution/tree/master/150-guild-command-not-found-using-remote-conda-environment

I think your best bet is NOT the symlink idea, but using the activation script to setup PATH to find Guild.

**Comment by SebastianCallh** [comment] 2020-03-18 15:11
Let's see if I understand the setup correctly. Initially I was thinking of it as 

`ssh -> actvate conda env -> run guild from inside conda -> guild runs code in conda env`

but I'm starting to think that the way it works is 

`ssh -> run guild in global scope -> guild starts the conda env -> guild runs the code in the conda env`

And the `venv-activate` would run between " run guild in global scope" and "guild starts the conda env" in the second description.

Am I understanding things properly?

>  Guild runs this before running anything else - so you will be able to set the PATH env to find Guild.

This confuses me a bit, and looks to me like modifying the path using `guild,` to be able to find `guild`. Could you please clarify?

**Comment by gar1t** [comment] 2020-05-26 22:20
Sorry for the late reply! Since the last exchange here there was some cleanup work on venv settings. Though from the notes here I don't know if those will address the situation.

To answer your question (I totally missed those - my apologies!), it's more like this:

```
guild -> ssh -> activate venv -> run guild cmd
```

Guild does not run in global scope if there's a venv configured for the remote. It always run within the activated env.

The issue as I understand it is that the `guild` exe is not accessible on the path after activation. If it's installed in the target venv and that venv is properly activated, it should be available.

I realize this might come a little late and you may not be in the middle of this over two months later! But if you're still having issue here, please feel to update here. I'll get back faster :)

**Comment by gar1t** [comment] 2020-07-28 16:35
I'm going to close this for now. If 0.7 is still exhibiting this problem let's reopen.

**Closed as completed by gar1t** 2020-07-28 16:35 UTC
Labels: bug
