### ISSUE TITLE
Tensorboard naming convention

### ISSUE THREAD

**Issue by melgor** [guildai/guildai#146] opened 2020-03-13 22:08 UTC
I have question about parametrising the name of experiment which occur in Tensorboard. Current one look like that:
```
{Guild-id} {script name} {parameters} {name given in script like save dir}
```
I have more tham 20 parametes what make such description unreadable. I would like to have just ID and save dir. It is possible using code from master?

**Comment by gar1t** [comment] 2020-03-14 20:54
Master is basically 0.7.0.rc9 - so no. But this is a good idea. What you're seeing there is the run `label` - Guild includes values like 'save dir' because they are flag values. Guild otherwise doesn't know anything about the types of flags or what they mean. It's just the label.

But as TensorBoard doesn't really give you a good way to name runs in the list, we generate directory names using ID, operation, and label.

I think we could add a `--run-name` option (or something like that) were you could specify how runs are named. E.g.

```
$ guild tensorboard --run-name .id =save-dir'
```

This is a funny looking pattern, but it uses Guild's _column spec_ syntax to specify a pattern that includes the run ID and the flag value for `save-dir`. E.g. this spec is used for specifying compare columns.

Given the need to release 0.7 ASAP, this feature would be deferred until the next minor release (e.g. 0.7.1) but I think it would be a nice change.

What do you think?

**Comment by gar1t** [comment] 2020-05-12 02:43
Okay - here's a proposal for 0.7 which will be in master shortly:

The `guild tensorboard` command will accept a new `--run-name-flags` option, which is a list of flag names (comma or space delimited). So to accomplish what you're looking for would be something like this:

    $ guild tensorboard --run-name-flags save-dir

I'm assuming the info "name given in script like save dir" is in a flag. If the value isn't in a flag, this scheme won't work.

**Comment by gar1t** [comment] 2020-05-26 22:25
A new option `--run-name-flags` is available for the `tensorboard` command. You can provide a list of flags (comma or space delimited) to specify which flags are used in the label (using the standard NAME=VAL, space delimited convention). You can specify an empty string to drop use flags altogether.

This will be available in the next release.

**Comment by gar1t** [comment] 2020-07-16 19:00
The fix is now generally available in 0.7.0. If this is still an issue, please re-open and we'll sort it out. Thanks again for the report!

**Closed as completed by gar1t** 2020-07-16 19:00 UTC

**Comment by christabella** [comment] 2020-09-15 15:18
Is there a way to reset the `--run-name-flags` config? It seems like I once ran it with `--run-name-flags "model_type"` and that worked, but now without the flag instead of reverting to the regular behaviour (displaying all flags) it became the empty behaviour (`--run-name-flags ""`).

(Slightly unrelated: space delimited `--run-name-flags "model_type covar_module"` did not work.)

**Comment by gar1t** [comment] 2020-09-15 15:50
Thanks for pointing out the bug there - neither space nor comma delimited lists work. This is fixed in master now.

I can't recreate the behavior you're describing with --run-name-flags being stuck in the empty behavior. To create a ran the Get Started `train.py` example three times with `x=[1,2,3]`. Then I used `--run-name-flags x` to confirm that only `x` is used. Then I omitted `--run-name-flags` and confirmed that both `x` and `noise` are used.

Guild doesn't cache anything that could cause the behavior you're describing so what you're seeing is surprising.

**Comment by christabella** [comment] 2020-09-15 16:33
Thank you for checking it out! Now that I look closely, it is actually the label that is interfering, as with the empty `--run-name-flags ""` the run name is plainly:
> `7a542ffa 1D:train-np 2020-09-15 18:04:01/summaries`

and without any `--run-name-flags`, the run name has the label "physionet_np_grid" appended to it as the default behaviour:
> `7a542ffa 1D:train-np 2020-09-15 18:04:01 physionet_np_grid/summaries`

Or maybe this is the expected behaviour when you label runs?

**Comment by gar1t** [comment] 2020-09-15 19:00
What you're seeing there is the intended behavior. The use of `--run-name-flags` overrides the default behavior, which is to show the label at that position.
