### ISSUE TITLE
Custom metrics in guild view

### ISSUE THREAD

**Issue by lambdaofgod** [guildai/guildai#51] opened 2019-08-16 13:39 UTC
Is there a way to add custom metrics (which can for example be seen in `guild compare`) to guild view?

If it's not, would it be hard to add that feature? It might be very useful for some tasks which do not conform to standard supervised learning setting

**Comment by gar1t** [comment] 2019-08-16 13:43
Yes, very possible! I'm a broken record on this point, but docs are missing this critical info - apologies! (Expecting to drop a new site with updated docs next week).

In the meantime, this example should get you going:

https://github.com/guildai/examples/tree/master/custom-scalars

**Comment by lambdaofgod** [comment] 2019-08-16 14:01
Sorry to reopen that, but it doesn't seem like these custom metrics appear in view. Do you think this might be related to #44 ?

Details: I've checked in logs in guild view, I've certainly logged my custom metric, but it still doesn't appear in view's dashboard.

**Comment by gar1t** [comment] 2019-08-16 14:17
Yes, #44 is the cause.

There's fix for this pending for the next release (0.6.6). There's a pre-release version available now (or will be in a few minutes depending on your platform) in 0.6.6.dev6. You can install this by running `pip install guildai --upgrade --pre`.

**Comment by gar1t** [comment] 2019-12-29 13:54
Closing as this was fixed for 0.6.6.

**Closed as completed by gar1t** 2019-12-29 13:54 UTC
